[package]
name = "lab-07"
version = "0.2.1"
edition = "2024"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
serde_json = "1.0"

[lints.rust]
unsafe_code = "forbid"
